export type Meal = {
  id: number; name: string; nameTe: string; desc: string;
  cat: string[]; veg: boolean; vegan?: boolean; glutenFree?: boolean;
  kcal: number; p: number; c: number; f: number; fiber: number; sugar: number; sodium: number;
  price: number; time: number; spice: 0 | 1 | 2 | 3; serving: string; pop: number; trending?: boolean;
  img: string; bg: string; allergens: string[]; ingredients: string; benefits: string[];
  bases?: string[];
};

export const CATS = [
  { k: "all", l: "All Meals" }, { k: "breakfast", l: "Breakfast" }, { k: "lunch", l: "Lunch" },
  { k: "dinner", l: "Dinner" }, { k: "snacks", l: "Snacks & Drinks" }, { k: "highprotein", l: "High Protein" },
  { k: "weightloss", l: "Weight Loss" }, { k: "musclegain", l: "Muscle Gain" }, { k: "keto", l: "Low Carb / Keto" },
  { k: "vegan", l: "Vegan" }, { k: "glutenfree", l: "Gluten-Free" }, { k: "indian", l: "Indian Meals" },
  { k: "mealprep", l: "Meal Prep Boxes" },
] as const;

export const ALLERGENS = ["Dairy", "Gluten", "Egg", "Peanuts", "Nuts", "Fish", "Sesame"] as const;

const RICE_BASES = ["White Rice", "Brown Rice", "Quinoa", "Millet"];

export const MEALS: Meal[] = [
  { id: 1, name: "Grilled Chicken & Steamed Veggies", nameTe: "గ్రిల్డ్ చికెన్ & వెజీస్", desc: "Lean grilled chicken with broccoli, beans, carrot medley & fresh lime.", cat: ["lunch","dinner","highprotein","musclegain","weightloss","mealprep"], veg: false, kcal: 430, p: 38, c: 28, f: 16, fiber: 6, sugar: 4, sodium: 520, price: 229, time: 20, spice: 1, serving: "1 box (350g)", pop: 98, trending: true, img: "🍗🥦", bg: "linear-gradient(135deg,#fde8cf,#f7c873)", allergens: [], ingredients: "Chicken breast, broccoli, green beans, carrot, bell pepper, olive oil, lime, herbs", benefits: ["High in protein — muscle growth & recovery","Rich in fiber — keeps you full longer","Heart-healthy fats"] },
  { id: 2, name: "Chicken Lime Fry + Dal Rice Bowl", nameTe: "చికెన్ లైమ్ ఫ్రై + దాల్ రైస్", desc: "Smoky chicken lime fry, ghee-tempered dal, herbed rice & salad.", cat: ["lunch","highprotein","musclegain","indian","mealprep"], veg: false, kcal: 422, p: 30, c: 44, f: 11, fiber: 13, sugar: 3, sodium: 610, price: 199, time: 25, spice: 2, serving: "1 plate (400g)", pop: 96, trending: true, img: "🍛🍗", bg: "linear-gradient(135deg,#fbe3c9,#f0a860)", allergens: ["Dairy"], ingredients: "Chicken, moong dal, rice, spring onion, lettuce, lime, spices", benefits: ["30g protein per plate","13g fiber from dal — 20% daily fiber","Supports heart & gut health"], bases: RICE_BASES },
  { id: 3, name: "Healthy Chicken Biryani", nameTe: "హెల్తీ చికెన్ బిర్యానీ", desc: "Protein-packed biryani with clean ingredients — flavour without the guilt.", cat: ["lunch","dinner","highprotein","indian"], veg: false, kcal: 520, p: 32, c: 58, f: 15, fiber: 5, sugar: 4, sodium: 740, price: 249, time: 35, spice: 3, serving: "1 tub (450g)", pop: 95, trending: true, img: "🍚🔥", bg: "linear-gradient(135deg,#fde5c0,#eda447)", allergens: ["Dairy"], ingredients: "Chicken, basmati rice, curd, mint, fried onion, boiled egg, biryani spices", benefits: ["Protein-packed & nutrient-rich","100% clean ingredients","Fat-loss friendly portioning"] },
  { id: 4, name: "Grilled Fish & Herb Mash", nameTe: "గ్రిల్డ్ ఫిష్ & మాష్", desc: "Pan-grilled fish fillets on lettuce with green-onion potato mash & lime.", cat: ["dinner","highprotein","weightloss","keto"], veg: false, kcal: 390, p: 34, c: 26, f: 15, fiber: 4, sugar: 2, sodium: 480, price: 249, time: 25, spice: 2, serving: "1 box (340g)", pop: 88, img: "🐟🥔", bg: "linear-gradient(135deg,#dbeef7,#8fc7de)", allergens: ["Fish"], ingredients: "Fish fillet, potato, spring onion, lettuce, lime, pepper, olive oil", benefits: ["Omega-rich lean protein","Light yet satisfying dinner","Supports recovery"] },
  { id: 5, name: "Tandoori Chicken Lettuce Plate", nameTe: "తందూరీ చికెన్ ప్లేట్", desc: "Char-grilled tandoori chicken with crisp iceberg & sautéed vegetables.", cat: ["dinner","highprotein","weightloss","keto"], veg: false, kcal: 340, p: 36, c: 12, f: 16, fiber: 5, sugar: 3, sodium: 560, price: 219, time: 22, spice: 3, serving: "1 plate (320g)", pop: 90, trending: true, img: "🍗🥬", bg: "linear-gradient(135deg,#fcd9c9,#ef9a6f)", allergens: ["Dairy"], ingredients: "Chicken, curd, tandoori spices, iceberg lettuce, broccoli, beans, carrot", benefits: ["Low carb, very high protein","Great for cutting phases","Char-grilled, not deep fried"] },
  { id: 6, name: "Spinach Dosa + Peanut Chutney", nameTe: "పాలకూర దోశ + పల్లీ చట్నీ", desc: "Iron-rich palak dosa with protein peanut chutney — South Indian & clean.", cat: ["breakfast","indian","weightloss"], veg: true, kcal: 250, p: 8, c: 30, f: 12, fiber: 4, sugar: 2, sodium: 390, price: 99, time: 15, spice: 2, serving: "2 dosas + chutney", pop: 87, img: "🥬🥞", bg: "linear-gradient(135deg,#e2f2d9,#9ccb84)", allergens: ["Peanuts"], ingredients: "Spinach, dosa batter, peanuts, green chilli, curry leaves", benefits: ["Iron boost — hemoglobin & blood health","Helps prevent anemia","Improves energy levels"] },
  { id: 7, name: "Millet Khichdi Bowl", nameTe: "మిల్లెట్ కిచిడీ", desc: "Comforting foxtail-millet khichdi with veggies, ghee & mild tempering.", cat: ["lunch","dinner","indian","weightloss","glutenfree"], veg: true, glutenFree: true, kcal: 360, p: 12, c: 52, f: 11, fiber: 8, sugar: 3, sodium: 450, price: 149, time: 20, spice: 1, serving: "1 bowl (380g)", pop: 82, img: "🥣🌾", bg: "linear-gradient(135deg,#f6ecd4,#dcbf7e)", allergens: ["Dairy"], ingredients: "Foxtail millet, moong dal, carrot, beans, peas, ghee, cumin", benefits: ["Millet-based & gluten-free","Easy on digestion","High fiber, steady energy"] },
  { id: 8, name: "Paneer Tawa Rice Bowl", nameTe: "పనీర్ తవా రైస్ బౌల్", desc: "Smoky tawa paneer over herbed rice with raita & fresh salad.", cat: ["lunch","dinner","highprotein","musclegain","indian"], veg: true, kcal: 450, p: 24, c: 48, f: 17, fiber: 5, sugar: 5, sodium: 590, price: 179, time: 22, spice: 2, serving: "1 bowl (400g)", pop: 89, trending: true, img: "🧀🍚", bg: "linear-gradient(135deg,#fdeed2,#f3bd6a)", allergens: ["Dairy"], ingredients: "Paneer, rice, capsicum, onion, tomato, curd raita, spices", benefits: ["24g vegetarian protein","Balanced macros for muscle gain","Home-cooked, never frozen"], bases: RICE_BASES },
  { id: 9, name: "Avocado Egg Power Toast", nameTe: "అవకాడో ఎగ్ టోస్ట్", desc: "Whole-wheat toast, mashed avocado & a chilli-flake fried egg.", cat: ["breakfast","highprotein","keto"], veg: false, kcal: 320, p: 15, c: 24, f: 18, fiber: 6, sugar: 2, sodium: 380, price: 149, time: 12, spice: 1, serving: "2 toasts + egg", pop: 85, img: "🥑🍳", bg: "linear-gradient(135deg,#e8f2d8,#b3d18a)", allergens: ["Gluten","Egg"], ingredients: "Whole-wheat bread, avocado, egg, chilli flakes, pepper, olive oil", benefits: ["Healthy monounsaturated fats","Keeps you full till lunch","Brain-food breakfast"] },
  { id: 10, name: "Oats & Fruit Protein Bowl", nameTe: "ఓట్స్ & ఫ్రూట్ బౌల్", desc: "Creamy chia-oats topped with apple, banana, pomegranate, nuts & raisins.", cat: ["breakfast","weightloss","snacks"], veg: true, kcal: 310, p: 11, c: 48, f: 9, fiber: 8, sugar: 18, sodium: 95, price: 99, time: 10, spice: 0, serving: "1 bowl (320g)", pop: 84, img: "🍌🍎", bg: "linear-gradient(135deg,#fdeccb,#f5c66b)", allergens: ["Nuts","Dairy"], ingredients: "Rolled oats, chia, milk, apple, banana, pomegranate, almonds, raisins", benefits: ["Fiber-rich morning start","Natural sugars only","Antioxidant boost from fruit"] },
  { id: 11, name: "Poha Classic", nameTe: "పోహా క్లాసిక్", desc: "Soft rice flakes with mustard seeds, peanuts, veggies & fresh curd side.", cat: ["breakfast","indian"], veg: true, kcal: 280, p: 7, c: 45, f: 8, fiber: 3, sugar: 3, sodium: 420, price: 79, time: 12, spice: 1, serving: "1 plate (280g)", pop: 80, img: "🍋🥜", bg: "linear-gradient(135deg,#fff3d1,#f8d878)", allergens: ["Peanuts","Dairy"], ingredients: "Poha, peanuts, onion, curry leaves, mustard seeds, lemon, curd", benefits: ["Light & energising","Classic Indian breakfast","Budget-friendly clean eating"] },
  { id: 12, name: "Millet / Quinoa Upma", nameTe: "మిల్లెట్ ఉప్మా", desc: "South-Indian style millet or quinoa upma with roasted nuts & pickle.", cat: ["breakfast","indian","glutenfree","weightloss"], veg: true, glutenFree: true, kcal: 290, p: 9, c: 42, f: 10, fiber: 6, sugar: 2, sodium: 410, price: 99, time: 15, spice: 1, serving: "1 bowl (300g)", pop: 78, img: "🌾🥗", bg: "linear-gradient(135deg,#f3edd7,#d3c37f)", allergens: ["Nuts"], ingredients: "Millet/quinoa, carrot, beans, peas, cashew, curry leaves, pickle", benefits: ["Gluten-free grains","Slow-release carbs","High-fiber energy start"] },
  { id: 13, name: "Masala Sprouts & Chickpea Bowl", nameTe: "మసాలా మొలకల బౌల్", desc: "Protein-rich sprouts, kidney beans & chickpeas with onion-tomato-lemon.", cat: ["breakfast","snacks","highprotein","vegan","weightloss","glutenfree"], veg: true, vegan: true, glutenFree: true, kcal: 240, p: 14, c: 34, f: 5, fiber: 9, sugar: 4, sodium: 300, price: 79, time: 8, spice: 2, serving: "1 bowl (250g)", pop: 83, img: "🌱🥣", bg: "linear-gradient(135deg,#e5f1da,#a8cd8b)", allergens: [], ingredients: "Moong sprouts, chickpeas, rajma, onion, tomato, green chilli, lemon", benefits: ["14g plant protein","Vegan & gluten-free","9g fiber — gut friendly"] },
  { id: 14, name: "American Breakfast Combo", nameTe: "అమెరికన్ బ్రేక్‌ఫాస్ట్", desc: "Egg your way + muesli, chicken sausage, toast & juice of the day.", cat: ["breakfast","highprotein","musclegain"], veg: false, kcal: 560, p: 28, c: 52, f: 24, fiber: 5, sugar: 14, sodium: 820, price: 289, time: 20, spice: 1, serving: "1 combo platter", pop: 86, img: "🍳🥓", bg: "linear-gradient(135deg,#fde4cd,#ef9f63)", allergens: ["Gluten","Egg","Dairy"], ingredients: "Eggs, muesli/cornflakes, chicken sausage, toast, seasonal juice", benefits: ["Full power breakfast","28g protein to start the day","Chef-style plating"] },
  { id: 15, name: "Rainbow Corn Veg Salad", nameTe: "రెయిన్‌బో కార్న్ సలాడ్", desc: "Sweet corn, cucumber, peppers, onion & lettuce in a light cream dressing.", cat: ["snacks","lunch","weightloss","glutenfree"], veg: true, glutenFree: true, kcal: 210, p: 6, c: 28, f: 9, fiber: 6, sugar: 8, sodium: 340, price: 99, time: 8, spice: 0, serving: "1 bowl (260g)", pop: 79, img: "🌽🥒", bg: "linear-gradient(135deg,#e9f4dc,#b8d98d)", allergens: ["Dairy"], ingredients: "Sweet corn, cucumber, capsicum, onion, cherry tomato, lettuce, light mayo", benefits: ["Low-calorie crunch","Vitamin-rich veggies","Great meal companion"] },
  { id: 16, name: "Protein Cold Coffee", nameTe: "ప్రోటీన్ కోల్డ్ కాఫీ", desc: "Whey-boosted cold coffee — high energy, low sugar, gym-bag ready.", cat: ["snacks","highprotein"], veg: true, kcal: 180, p: 20, c: 14, f: 4, fiber: 0, sugar: 6, sodium: 120, price: 99, time: 5, spice: 0, serving: "1 glass (350ml)", pop: 81, trending: true, img: "🥤☕", bg: "linear-gradient(135deg,#ead9c6,#b98e63)", allergens: ["Dairy"], ingredients: "Milk, whey protein, coffee, cocoa drizzle, stevia", benefits: ["20g protein per glass","Low sugar option","Perfect pre/post-workout"] },
  { id: 17, name: "Brown Bread & Fruit Box", nameTe: "బ్రెడ్ & ఫ్రూట్ బాక్స్", desc: "Whole-wheat sandwich with a rainbow fruit mix — mango, melon, grapes & more.", cat: ["snacks","breakfast","weightloss"], veg: true, kcal: 260, p: 8, c: 46, f: 5, fiber: 6, sugar: 20, sodium: 280, price: 79, time: 8, spice: 0, serving: "1 box (300g)", pop: 76, img: "🍉🥪", bg: "linear-gradient(135deg,#fde7d2,#f5b477)", allergens: ["Gluten"], ingredients: "Whole-wheat bread, seasonal fruits — mango, papaya, watermelon, grapes", benefits: ["Natural vitamins & hydration","Office-friendly snack box","Fresh cut daily"] },
  { id: 18, name: "Ragi Roti Grill Box", nameTe: "రాగి రొట్టె గ్రిల్ బాక్స్", desc: "Ragi rotis with your choice of veg / non-veg grill, salad & juice.", cat: ["dinner","indian","highprotein","weightloss","mealprep"], veg: false, kcal: 410, p: 26, c: 44, f: 13, fiber: 7, sugar: 5, sodium: 540, price: 199, time: 25, spice: 2, serving: "1 box (380g)", pop: 85, img: "🫓🔥", bg: "linear-gradient(135deg,#efe3d1,#c9a976)", allergens: ["Dairy"], ingredients: "Ragi flour, grilled chicken/paneer, salad, night detox juice", benefits: ["Ragi — calcium & iron rich","Light yet satisfying dinner","Supports recovery overnight"] },
  { id: 19, name: "Pesarattu + Ginger Chutney", nameTe: "పెసరట్టు + అల్లం చట్నీ", desc: "Andhra-style green-gram dosa with allam chutney — protein the desi way.", cat: ["breakfast","indian","highprotein","vegan","glutenfree"], veg: true, vegan: true, glutenFree: true, kcal: 270, p: 13, c: 38, f: 7, fiber: 6, sugar: 2, sodium: 360, price: 89, time: 15, spice: 2, serving: "2 pesarattu + chutney", pop: 88, img: "🟢🥞", bg: "linear-gradient(135deg,#e3f0d6,#96c47c)", allergens: [], ingredients: "Whole moong, ginger, green chilli, cumin, onion", benefits: ["Andhra classic, protein-rich","Vegan & gluten-free","Low oil preparation"] },
  { id: 20, name: "Falafel Cutlets + Mint Sauce", nameTe: "ఫలాఫెల్ కట్లెట్స్", desc: "Crisp baked falafel patties with cooling mint yogurt dip.", cat: ["snacks","highprotein"], veg: true, kcal: 300, p: 12, c: 32, f: 14, fiber: 8, sugar: 3, sodium: 460, price: 99, time: 15, spice: 2, serving: "4 cutlets + dip", pop: 77, img: "🧆🌿", bg: "linear-gradient(135deg,#efe9d3,#c9bd7d)", allergens: ["Dairy","Sesame"], ingredients: "Chickpeas, herbs, sesame, spices, curd-mint dip", benefits: ["Plant-protein snack","Baked, not deep fried","8g fiber per serve"] },
];

export const getMeal = (id: number) => MEALS.find((m) => m.id === id);
